#!/bin/bash


N_ELS=102400
T_OUT=10

make clean_all;
make test_c_tm DEF1=COMMITS_ONLY DEF2=DISABLE_NOTHING ;


for N_TH in 2 4 ; do
	for W_Q in 0 10 20 30 40 50 60 70 80 90 100; do
		for N_PER_TX in 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500; do
			for (( i=0; i<3; i++ )); do
#				./test_c_tm 1 1 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 1 2 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 1 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 2 1 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 2 2 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 2 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 3 2 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 3 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 4 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
			done;
		done;
	done;
done;



N_ELS=1024
T_OUT=10

make clean_all;
make test_c_tm DEF1=COMMITS_ONLY DEF2=DISABLE_NOTHING ;


for N_TH in 2 4 ; do
	for W_Q in 0 10 20 30 40 50 60 70 80 90 100; do
		for N_PER_TX in 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150; do
			for (( i=0; i<3; i++ )); do
#				./test_c_tm 1 1 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 1 2 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 1 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 2 1 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 2 2 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 2 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 3 2 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
#				./test_c_tm 3 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
				./test_c_tm 4 3 ${N_TH} ${N_ELS} ${N_PER_TX} ${W_Q} ${T_OUT}   test_${N_TH}_${N_ELS}_${W_Q}.out  ;
			done;
		done;
	done;
done;

